server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
        - id: record
          uri: lb://RECORD-SERVICE
          predicates:
            - Path=/api/v1/record/**

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
    register-with-eureka: true

