server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/user-service
    username: madushan
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka